# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.cache/wt [current_project]
set_property parent.project_path E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs [current_project]
update_ip_catalog
set_property ip_output_repo e:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/soft/test.coe
add_files E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/soft/mips1.coe
add_files E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/soft/mips2.coe
add_files E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/soft/mips3.coe
add_files E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/soft/test1.coe
add_files E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/soft/count_from_0.coe
read_verilog E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/mycpu/macro.vh
read_verilog -library xil_defaultlib {
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/mycpu/alu.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/confreg/confreg.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/mycpu/control.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/mycpu/cpu.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/mycpu/exe_mem.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/mycpu/id_exe.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/mycpu/if_id.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/mycpu/mem_wb.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/mycpu/pc.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/mycpu/regfile.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/mycpu/stall.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/vga.v
  E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/top_pipeline.v
}
read_ip -quiet E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all e:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/ip/data_ram/data_ram_ooc.xdc]

read_ip -quiet E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/ip/inst_rom/inst_rom.xci
set_property used_in_implementation false [get_files -all e:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/ip/inst_rom/inst_rom_ooc.xdc]

read_ip -quiet E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/ip/clk_wiz/clk_wiz.xci
set_property used_in_implementation false [get_files -all e:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/ip/clk_wiz/clk_wiz_board.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/ip/clk_wiz/clk_wiz.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/sources_1/new/ip/clk_wiz/clk_wiz_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/constrs_1/new/port_light_control.xdc
set_property used_in_implementation false [get_files E:/Xilinx/pipelinecpu/pipelinecpu/pipelinecpu.srcs/constrs_1/new/port_light_control.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_pipeline -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_pipeline.dcp
create_report "synth_4_synth_report_utilization_0" "report_utilization -file top_pipeline_utilization_synth.rpt -pb top_pipeline_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
