# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/port_light_control.xdc

# IP: new/ip/data_ram/data_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet
