# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/workplace/Vivado/SSRCPU/SSR_CPU/single_cycle/single_cycle.srcs/sources_1/new/ip/inst_rom/inst_rom.xci
# IP: The module: 'inst_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/workplace/Vivado/SSRCPU/SSR_CPU/single_cycle/single_cycle.srcs/sources_1/new/ip/inst_rom/inst_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/workplace/Vivado/SSRCPU/SSR_CPU/single_cycle/single_cycle.srcs/sources_1/new/ip/inst_rom/inst_rom.xci
# IP: The module: 'inst_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/workplace/Vivado/SSRCPU/SSR_CPU/single_cycle/single_cycle.srcs/sources_1/new/ip/inst_rom/inst_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
